---
- hosts: 127.0.0.1
  connection: local
  remote_user: vagrant
  become: yes
  vars:
    users:
    - "jenkins"

  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"

  - name:   Create admin file if does not exist
    file:
      path: "/etc/sudoers.d/admin"
      state: touch

  - name: "Allow vagrant users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers.d/admin" # path: in version 2.3
      state: "present"
      line: "jenkins ALL=(ALL) NOPASSWD: ALL"